app/views/layouts/application.html.erb
=> fixed js tag

app/controllers/barcodes_controller.rb, app/views/barcodes/index.html.erb, config/routes.rb, package-lock.json, package.json, test/controllers/barcodes_controller_test.rb, yarn.lock
I've created a barcode reader using https://zxing-js.github.io/library/. The code works as it is in  but I've had issues trying to place the javascript in a separate js file - can anyone help with it?
=> created a first barcode reader - to be updated

app/assets/stylesheets/components/_video.scss, app/javascript/controllers/barcode_reader_controller.js, app/views/products/new.html.erb
changing onClick to video-container, not just video.
=> fix: increase video selection to video container

app/models/favorite.rb, db/migrate/20230222202816_create_favorites.rb, db/schema.rb, test/models/favorite_test.rb
Quickly adding favorites to our DB!
=> feat: added favorites to db

db/schema.rb
Adding barcode back to products model
=> fix: adding barcode back

app/assets/stylesheets/pages/_home.scss, app/javascript/controllers/application.js, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
The headline effect might not be very disable friendly
In details:
- headline glowing effect
- learn more btn have hovering enlargement effect
- paragraphs have appear/disappear effect when scrolling
- download btn size is flashing
=> Animation elements

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_products_show.scss, app/controllers/products_controller.rb, app/models/favorite.rb, app/models/product.rb, app/models/user.rb, app/views/products/show.html.erb, config/initializers/acts_as_favoritor.rb, config/routes.rb, db/migrate/20230225125208_change_retail_price_to_string_in_products.rb, db/migrate/20230225131214_acts_as_favoritor_migration.rb, db/migrate/20230225135658_add_image_url_to_products.rb, db/schema.rb, db/seeds.rb
I add the act_as_favoritor gem to make the logic and associated methods easier. Now it's built in! 
I created some little icons and text to accompany the logic in the products#show page, so now we have that and the style can be improved upon if needed.
I also added an image to make the app a bit less dull. In the #show page, I left the link of the product I was testing, but if you're testing the barcode, you can remove this and replace the image link with @product.url_image.
Let me know if you have any questions!
=> Favorites products

app/views/pages/welcome.html.erb
- Used aria label to improve readability for screen reader ussers
- Small change to button labels to make them clearer
=> Fixed page for screen readers

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/products_controller.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/products/show.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20230227140231_add_omniauth_provider_to_users.rb, db/schema.rb
- User now needs to be logged in or signed up to save a product;
- After log in, they are redirected to the same product page
- Styled the sign in / sign up pages and social login buttons
6b9db1.png)
=> User is asked to log in to save a product and redirected to product page

app/controllers/products_controller.rb, app/javascript/controllers/barcode_reader_controller.js
Bringing up the error logic so that it is found if the product barcode is not located.
=> Products error on barcode

app/assets/stylesheets/components/_video.scss, app/javascript/controllers/barcode_reader_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/quagga_barcode_reader_controller.js, app/views/products/index.html.erb, package-lock.json, package.json, yarn.lock
Please test this on mobile and let me know! You can find the new barcode reader in the products/index page.
=> Testing the QuaggaJS barcode reader

app/javascript/controllers/quagga_barcode_reader_controller.js, app/views/products/index.html.erb, app/views/products/new.html.erb, db/schema.rb
Changed a few config in the Quagga controller to improve accuracy. Please test it with Sephora products and let me know!
=> changed a few barcode reader config for testing

Procfile.dev, app/assets/config/manifest.js, app/assets/stylesheets/application.sass.scss, package.json, yarn.lock
Went through about 10+ articles, docs and StackOverflow articles, but I think [this one](https://stackoverflow.com/questions/70482086/rails-7-0-esbuild-running-app-gives-error-command-build-not-found) might solve our build:css issue. 
With the changes that came from running some of the commands, I was able to precompile the assets. We'll see if this works once pushed to Render.
=> fix: hoping this fixes our build:css issue

Gemfile, Gemfile.lock, Procfile.dev, app/assets/config/manifest.js
Reverts SIFAR101/Illuminate#58
=> Revert "fix: removed css bundling and replaced with dartsass rails"

app/views/layouts/application.html.erb, package.json
Trying another fix for the JS problem in render.
=> fix: changed  js tag in appli.html.erb

app/javascript/controllers/barcode_reader_controller.js, app/views/pages/welcome.html.erb
- The camera should now start as soon as you open the 'Scan' page;
- Camera will activate on camera page, and deactivate if a product is found OR if the user navigates to another window. It takes a couple of seconds for the camera to switch off, but it should work correctly. 
- Added logic to the login/sign up button on the 'welcome' page.
It looks to be like it works correctly on every page, but please do let me know if you notice any issues!!
=> fixed camera issue

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_user_favorites.scss, app/controllers/products_controller.rb, app/views/products/show.html.erb, app/views/products/user_favorites.html.erb, app/views/shared/_card.html.erb
I added a new issue for this, but it would be good to add a search feature on this page.
=> fix: added some styling to user_favorites page and ordering favorites by brand name

app/javascript/controllers/favorite_controller.js, app/views/products/show.html.erb, app/views/shared/_favorite.html.erb
No major changes. I just took the Favorites section in the #show page and moved it to a partial.
=> Favorites stimulus

app/controllers/users/sessions_controller.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/pages/home.html.erb, app/views/products/new.html.erb, app/views/products/show.html.erb, app/views/shared/_flashes.html.erb, app/views/shared/_navbar.html.erb
First improvement of aria labels and alt tags. There's still some work to be done, but we will need to go over it once the app is finalised.
=> improved aria labels and alt tags

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/pages/privacy.html.erb, app/views/pages/terms.html.erb, config/routes.rb
=> Privacy policy

app/assets/stylesheets/components/_button.scss, app/controllers/products_controller.rb, app/views/shared/_favorite.html.erb, config/routes.rb
I added an 'unfavorite' method in the products controller. I think it works as it should, I'd appreciate if someone could test it too!
=> Added unfavorite
